Repository Twilight-Studioo/production, pull requests merged in 2024-10, with the labels that each got.

#209 :recycle: refactor: `ObjectFactory` をシングルトンクラスに変更
  src/Assets/Scenes/Tests/DroneTest.unity
  src/Assets/Scripts/Core/Utilities/GizmoManager.cs
  src/Assets/Scripts/Core/Utilities/Health/HealthBarManager.cs
  src/Assets/Scripts/Core/Utilities/ObjectFactory.cs
  src/Assets/Scripts/Feature/Component/Enemy/DroneAgent.cs
  src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy1Agent.cs
  src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs
  src/Assets/Scripts/Feature/Component/Environment/ItemSpawner.cs
  src/Assets/Scripts/Feature/Component/Environment/PlayerStart.cs
  src/Assets/Scripts/Feature/Interface/IEnemyAgent.cs
  src/Assets/Scripts/Feature/Presenter/EnemyPresenter.cs
  src/Assets/Scripts/Feature/View/PlayerView.cs
  src/Assets/Scripts/Main/Controller/MainController.cs
  src/Assets/Scripts/Main/Factory/EnemyFactory.cs
Labels: wontfix, self

#217 :bug: fix: Item spawning distanceチェックの修正
  src/Assets/Scripts/Feature/Component/Environment/ItemSpawner.cs
Labels: bug

#250 Design/convey
  src/Assets/Contents/Gimmicks/Convey.meta
  src/Assets/Contents/Gimmicks/Convey/Model.meta
  src/Assets/Contents/Gimmicks/Convey/Model/conveyoEndPort.fbx
  src/Assets/Contents/Gimmicks/Convey/Model/conveyoEndPort.fbx.meta
  src/Assets/Contents/Gimmicks/Convey/Model/conveyoExpand.fbx
  src/Assets/Contents/Gimmicks/Convey/Model/conveyoExpand.fbx.meta
  src/Assets/Contents/Gimmicks/Convey/Model/conveyoMiddle.fbx
  src/Assets/Contents/Gimmicks/Convey/Model/conveyoMiddle.fbx.meta
  src/Assets/Prefabs/AccelerationPlate.prefab
Labels: review
