Repository Twilight-Studioo/production, pull requests merged in 2024-11, with the labels that each got.

#261 UIナビゲーションとコントローラー実装
  src/Assets/Editor/Tests/Main/InjectionEditModeTests.cs
  src/Assets/Prefabs/System/Statics.prefab
  src/Assets/Prefabs/UI/ControlsScreen.prefab
  src/Assets/Prefabs/UI/ControlsScreen.prefab.meta
  src/Assets/Prefabs/UI/OptionCanvas.prefab
  src/Assets/Prefabs/UI/OptionCanvas.prefab.meta
  src/Assets/Prefabs/UI/PauseCanvas.prefab
  src/Assets/Prefabs/UI/PauseCanvas.prefab.meta
  src/Assets/Prefabs/UI/VolumesCanvas.prefab
  src/Assets/Prefabs/UI/VolumesCanvas.prefab.meta
  src/Assets/Scripts/Core/Input/Generated/ActionGuid.cs
  src/Assets/Scripts/Core/Input/InputActionEvent.cs
  src/Assets/Scripts/Core/Input/InputActionGenerator.cs
  src/Assets/Scripts/Core/Navigation/Core.Navigation.asmdef
  src/Assets/Scripts/Core/Navigation/Default.cs
  src/Assets/Scripts/Core/Navigation/Default.cs.meta
  src/Assets/Scripts/Core/Navigation/IScreen.cs
  src/Assets/Scripts/Core/Navigation/ScreenController.cs
  src/Assets/Scripts/Core/Navigation/ScreenControllerLogic.cs
  src/Assets/Scripts/Core/Navigation/ScreenControllerLogic.cs.meta
  src/Assets/Scripts/Core/Navigation/ScreenControllerUtils.cs
  src/Assets/Scripts/Core/Navigation/ScreenControllerUtils.cs.meta
  src/Assets/Scripts/Core/Navigation/ScreenRecord.cs
  src/Assets/Scripts/Core/Utilities/NullChecker.cs
  src/Assets/Scripts/Core/Utilities/NullChecker.cs.meta
  src/Assets/Scripts/Feature/Interface/IInputController.cs
  src/Assets/Scripts/Feature/Interface/IInputController.cs.meta
  src/Assets/Scripts/Main/Controller/GameManager.cs
  src/Assets/Scripts/Main/Controller/GameNavigation.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/ControlsScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ControlsScreen.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/Navigation.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/Navigation.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/OptionScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/OptionScreen.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/PauseScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/PauseScreen.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocol.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocol.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocolLogic.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocolLogic.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/VolumesScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/VolumesScreen.cs.meta
  src/Assets/Scripts/Main/Controller/InputController.cs
  src/Assets/Scripts/Main/Controller/InputController.cs.meta
  src/Assets/Scripts/Main/Installer/MainInstaller.cs
  src/Assets/Scripts/Main/Main.asmdef
  src/Assets/Settings/Input/InputPlayer.inputactions
Labels: review

#238 Feature/battle camera
  src/Assets/Prefabs/Camera.prefab
  src/Assets/Prefabs/Dagger.prefab
  src/Assets/Prefabs/slash1.prefab
  src/Assets/Scenes/Template/StageTemplate.scenetemplate
  src/Assets/Scenes/Tests/BattleCamera.meta
  src/Assets/Scenes/Tests/BattleCamera.unity
  src/Assets/Scenes/Tests/BattleCamera.unity.meta
  src/Assets/Scenes/Tests/BattleCamera/BeamEffect.prefab
  src/Assets/Scenes/Tests/BattleCamera/BeamEffect.prefab.meta
  src/Assets/Scenes/Tests/BattleCamera/BeamPlane.fbx
  src/Assets/Scenes/Tests/BattleCamera/BeamPlane.fbx.meta
  src/Assets/Scenes/Tests/BattleCamera/beam3_alpha.png
  src/Assets/Scenes/Tests/BattleCamera/beam3_alpha.png.meta
  src/Assets/Scenes/Tests/BattleCamera/gradient.png
  src/Assets/Scenes/Tests/BattleCamera/gradient.png.meta
  src/Assets/Scenes/Tests/BattleCamera/gradient_alpha.png
  src/Assets/Scenes/Tests/BattleCamera/gradient_alpha.png.meta
  src/Assets/Scenes/Tests/Player_animation.unity
  src/Assets/Scripts/Core/Camera/CameraTargetGroupTag.cs
  src/Assets/Scripts/Core/Camera/TargetGroupManager.cs
  src/Assets/Scripts/Feature/Component/Dagger.cs
  src/Assets/Scripts/Feature/View/PlayerView.cs
Labels: review

#272 Feature/slash voltage
  src/Assets/Contents/Player/Animation/MOCAP_0826/player_attackA.fbx.meta
  src/Assets/Contents/Player/Animation/MOCAP_0826/player_attackB.fbx.meta
  src/Assets/Contents/Player/Animation/MOCAP_0826/player_attackC.fbx.meta
  src/Assets/Prefabs/Player/Dagger.prefab
  src/Assets/Prefabs/Player/Player.prefab
  src/Assets/Prefabs/slashNormal1.prefab
  src/Assets/Prefabs/slashNormal1.prefab.meta
  src/Assets/Prefabs/slashNormal2.prefab
  src/Assets/Prefabs/slashNormal2.prefab.meta
  src/Assets/Prefabs/slashNormal3.prefab
  src/Assets/Prefabs/slashNormal3.prefab.meta
  src/Assets/Scenes/Tests/CameraTest.unity
  src/Assets/Scenes/Tests/SoundTest.unity
  src/Assets/Scripts/Feature/Common/Parameter/CharacterParams.cs
  src/Assets/Scripts/Feature/Common/Parameter/CharacterParamsEditor.cs
  src/Assets/Scripts/Feature/Component/PlayerAnimation.cs
  src/Assets/Scripts/Feature/Component/PlayerAnimation.cs.meta
  src/Assets/Scripts/Feature/Interface/IPlayerView.cs
  src/Assets/Scripts/Feature/Presenter/PlayerPresenter.cs
  src/Assets/Scripts/Feature/View/PlayerView.cs
  src/Assets/Settings/CharacterParams.asset
Labels: program, review

#280 :sparkles: feat: タイトル画面とシーンローダーの追加
  .github/workflows/unity_build_on_devops.yml
  src/Assets/Editor/Tests/Main/InjectionEditModeTests.cs
  src/Assets/Prefabs/System/Env.prefab
  src/Assets/Prefabs/System/RootInstaller.prefab
  src/Assets/Prefabs/System/RootInstaller.prefab.meta
  src/Assets/Prefabs/System/Statics.prefab
  src/Assets/Prefabs/System/TitleStatics.prefab
  src/Assets/Prefabs/System/TitleStatics.prefab.meta
  src/Assets/Prefabs/UI/TitleCanvas.prefab
  src/Assets/Prefabs/UI/TitleCanvas.prefab.meta
  src/Assets/Scenes/OutGame.meta
  src/Assets/Scenes/OutGame/TitleScene.unity
  src/Assets/Scenes/OutGame/TitleScene.unity.meta
  src/Assets/Scripts/Core/Utilities/SceneUtility.cs
  src/Assets/Scripts/Core/Utilities/SceneUtility.cs.meta
  src/Assets/Scripts/Feature/Interface/IGameInputController.cs
  src/Assets/Scripts/Feature/Interface/IGameInputController.cs.meta
  src/Assets/Scripts/Feature/Interface/ISceneDataModel.cs
  src/Assets/Scripts/Feature/Interface/ISceneDataModel.cs.meta
  src/Assets/Scripts/Feature/Interface/ITitleController.cs
  src/Assets/Scripts/Feature/Interface/ITitleController.cs.meta
  src/Assets/Scripts/Main/Controller/GameController.cs
  src/Assets/Scripts/Main/Controller/GameController.cs.meta
  src/Assets/Scripts/Main/Controller/GameInputController.cs
  src/Assets/Scripts/Main/Controller/GameInputController.cs.meta
  src/Assets/Scripts/Main/Controller/GameManager.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ControlsScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/Navigation.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/OptionScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/PauseScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocol.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocolLogic.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/TitleScreen.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/TitleScreen.cs.meta
  src/Assets/Scripts/Main/Controller/GameNavigation/VolumesScreen.cs
  src/Assets/Scripts/Main/Controller/TitleController.cs
  src/Assets/Scripts/Main/Controller/TitleController.cs.meta
  src/Assets/Scripts/Main/Controller/TitleManager.cs
  src/Assets/Scripts/Main/Controller/TitleManager.cs.meta
  src/Assets/Scripts/Main/Installer/GameInstaller.cs
  src/Assets/Scripts/Main/Installer/GameInstaller.cs.meta
  src/Assets/Scripts/Main/Installer/RootInstaller.cs
  src/Assets/Scripts/Main/Installer/RootInstaller.cs.meta
  src/Assets/Scripts/Main/Installer/TitleInstaller.cs
  src/Assets/Scripts/Main/Installer/TitleInstaller.cs.meta
  src/Assets/Scripts/Main/Scene.meta
  src/Assets/Scripts/Main/Scene/Generated.meta
  src/Assets/Scripts/Main/Scene/Generated/SceneLoader.cs
  src/Assets/Scripts/Main/Scene/Generated/SceneLoader.cs.meta
  src/Assets/Scripts/Main/Scene/Generated/Scenes.cs
  src/Assets/Scripts/Main/Scene/Generated/Scenes.cs.meta
  src/Assets/Scripts/Main/Scene/RootInstance.cs
  src/Assets/Scripts/Main/Scene/RootInstance.cs.meta
  src/Assets/Settings/VContainerSettings.asset
  src/Assets/Settings/VContainerSettings.asset.meta
  src/Assets/TextMesh Pro/Resources/Fonts & Materials/DelaGothicOne-Regular SDF.asset
  src/ProjectSettings/EditorBuildSettings.asset
  src/ProjectSettings/Packages/com.unity.services.core/Settings.json
  src/ProjectSettings/ProjectSettings.asset
Labels: help wanted, wontfix, program, self, review

#287 :bug: fix: 地面との距離チェックを追加
  src/Assets/Scripts/Feature/View/PlayerView.cs
Labels: review

#314 Feature/smasher stage
  src/Assets/Contents/UI.meta
  src/Assets/Contents/UI/HP.meta
  src/Assets/Contents/UI/HP/HP4.PNG
  src/Assets/Contents/UI/HP/HP4.PNG.meta
  src/Assets/Contents/UI/HP/HP_1.PNG
  src/Assets/Contents/UI/HP/HP_1.PNG.meta
  src/Assets/Contents/UI/HP/HP_2.PNG
  src/Assets/Contents/UI/HP/HP_2.PNG.meta
  src/Assets/Contents/UI/HP/HP_3.PNG
  src/Assets/Contents/UI/HP/HP_3.PNG.meta
  src/Assets/Contents/UI/stamina_1.PNG
  src/Assets/Contents/UI/stamina_1.PNG.meta
  src/Assets/Contents/UI/stamina_2.PNG
  src/Assets/Contents/UI/stamina_2.PNG.meta
  src/Assets/Contents/UI/stamina_3.PNG
  src/Assets/Contents/UI/stamina_3.PNG.meta
  src/Assets/Contents/UI/stamina_4.PNG
  src/Assets/Contents/UI/stamina_4.PNG.meta
  src/Assets/Prefabs/System/Canvas.prefab
  src/Assets/Scenes/SmasherStage.meta
  src/Assets/Scenes/SmasherStage/SmasherStage.unity
  src/Assets/Scenes/SmasherStage/SmasherStage.unity.meta
  src/Assets/Scripts/Feature/Component/PlayerHPBar.cs
  src/Assets/Scripts/Feature/View/GameUIView.cs
Labels: program

#316 :recycle: refactor: scriptableObjectのパラメータ自動グループ化を実装
  src/Assets/Editor/Tests/Common/Editor.Tests.Common.asmdef
  src/Assets/Editor/Tests/Model/Editor.Tests.Model.asmdef
  src/Assets/Scripts/Core/Utilities/Parameter.meta
  src/Assets/Scripts/Core/Utilities/Parameter/BaseParameter.cs
  src/Assets/Scripts/Core/Utilities/Parameter/BaseParameter.cs.meta
  src/Assets/Scripts/Core/Utilities/Parameter/SimpleEditor.cs
  src/Assets/Scripts/Core/Utilities/Parameter/SimpleEditor.cs.meta
  src/Assets/Scripts/Core/Utilities/Parameter/ToggleGroup.cs
  src/Assets/Scripts/Core/Utilities/Parameter/ToggleGroup.cs.meta
  src/Assets/Scripts/Feature/Common/Constants/EnemyParams.cs
  src/Assets/Scripts/Feature/Common/Constants/Feature.Common.Constants.asmdef
  src/Assets/Scripts/Feature/Common/Parameter/CharacterParams.cs
  src/Assets/Scripts/Feature/Common/Parameter/DroneParams.cs
  src/Assets/Scripts/Feature/Common/Parameter/Feature.Common.Parameter.asmdef
  src/Assets/Scripts/Feature/Common/Parameter/SimpleEnemy1Params.cs
  src/Assets/Scripts/Feature/Common/Parameter/SimpleEnemy2Params.cs
Labels: review
