Repository Twilight-Studioo/production, pull requests merged in 2025-01, with the labels that each got.

#367 superObjectが遷移で破棄されないように修正
  src/Assets/Scripts/Core/Utilities/ObjectFactory.cs
  src/Assets/Scripts/Feature/View/EnemyView.cs
Labels: review

#391 敵アニメーション修正
  src/Assets/Scenes/Tests/BattleCamera.unity
  src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy1Agent.cs
  src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2Agent.cs
  src/Assets/Scripts/Feature/Component/Enemy/SimpleEnemy2FlyAgent.cs
  src/ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: program

#410 ボス戦でリトライできない問題の修正
  src/Assets/Scenes/Zako/zako.unity
  src/Assets/Scripts/Core/Camera/TargetGroupManager.cs
  src/Assets/Scripts/Core/Navigation/IScreen.cs
  src/Assets/Scripts/Core/Navigation/ScreenControllerLogic.cs
  src/Assets/Scripts/Core/Utilities/SceneUtility.cs
  src/Assets/Scripts/Feature/Component/FixedLoadSceneArea.cs
  src/Assets/Scripts/Main/Controller/EndfieldController.cs
  src/Assets/Scripts/Main/Controller/GameNavigation/ScreenProtocol.cs
  src/Assets/Scripts/Main/Installer/RootInstaller.cs
  src/Assets/Scripts/Main/Scene/FixedLoadSceneArea.cs
  src/Assets/Scripts/Main/Scene/FixedLoadSceneArea.cs.meta
  src/Assets/Scripts/Main/Scene/Generated/SceneLoader.cs
  src/Assets/Scripts/Main/Scene/Generated/Scenes.cs
  src/Assets/Scripts/Main/Scene/RootInstance.cs
  src/Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: bug, self, review
